[package]
name = "num2english"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigfloat = "1.6.2"
num-bigint = "0.4.3"
